# Settings in the [build] context are global and are applied to all contexts 
# unless otherwise overridden by more specific contexts.  
[build]
  # Default build command.
  command = "gatsby build && subfont public -i"
